### ISSUE TITLE
Find suitable WISH event file

### ISSUE THREAD

**Issue by mattclarke** [ScreamingUdder/isis_issues#3]
Would a vanadium file be suitable?

**Comment by matthew-d-jones** [comment]
Pascal says:
`You can pick any between 34506 to 34512.
The issue is where the flux is biggest (single frame to 110 000 microsec) we ran in histo mode but for double frame (0 to 206 000 microsec) we ran in event. As a rule, if we run something that we know will be massive, we try in histo (but it is not possible for double frame as we do not have enough time channels).`

**Comment by mattclarke** [comment]
From Paz:

> You can pick any between 34506 to 34512.
> The issue is where the flux is biggest (single frame to 110 000 microsec) we ran in histo mode but for double frame (0 to 206 000 microsec) we ran in event. As a rule, if we run something that we know will be massive, we try in histo (but it is not possible for double frame as we do not have enough time channels).
